<template>
  <view :class="['app-page','workbench-detail',{dark}]">
    <ui-header title="履约订单详情" back />
    <template v-if="order">
      <view class="summary"><view><text class="section-title">{{order.productName}}</text><text class="muted">{{order.skuName}} × {{order.qty}}</text></view><ui-status-tag :label="statusName(order.status)" :tone="statusTone(order.status)"/></view>
      <view class="card"><text class="section-title">履约资料</text><view v-for="item in detailRows" :key="item.label" class="row"><text>{{item.label}}</text><text selectable>{{item.value||'-'}}</text></view></view>
      <view class="card"><text class="section-title">订单流转</text><view v-for="log in order.logs||[]" :key="log.id" class="log"><view><text>{{statusName(log.fromStatus)}} → {{statusName(log.toStatus)}}</text><text class="muted">{{displayDateTime(log.createdAt)}}</text></view><text class="muted">{{log.note||'-'}}</text></view></view>
      <view v-if="order.aftersale&&order.aftersale.length" class="card link" @tap="openAfterSale(order.aftersale[0])"><view><text class="section-title">售后申请</text><text class="muted">{{order.aftersale[0].aftersaleNo}} · {{order.aftersale[0].status}}</text></view><ui-icon name="chevron-right" :size="30"/></view>
      <view v-if="(order.allowedActions||[]).length" class="actions"><view v-if="allowed('reject')" class="secondary-btn" @tap="act('reject')">拒单申请退款</view><view v-if="allowed('accept')" class="primary-btn" @tap="act('accept')">确认接单</view><view v-if="allowed('start')" class="primary-btn" @tap="act('start')">开始服务</view><view v-if="allowed('finish')" class="primary-btn" @tap="act('finish')">完成服务</view></view>
    </template>
    <ui-page-status v-else :loading="loading" title="订单详情加载失败" :description="error" @retry="load"/>
  </view>
</template>
<script>
import{api}from'@/services/api';import{isDark}from'@/utils/app'
import {occupancyClock} from "@/services/occupancy-clock.mjs"
export default{mixins:[occupancyClock],data(){return{dark:false,id:'',order:null,loading:true,error:''}},computed:{detailRows(){const o=this.order||{};return[{label:'订单号',value:o.orderNo},{label:'游戏ID',value:o.gameId},{label:'游戏昵称',value:o.gameNickname},{label:'联系人',value:o.contactName||'未填写'},{label:'联系电话',value:o.contactPhone||'当前阶段不可见'},{label:'用户备注',value:o.remark||'无'},{label:'实付金额',value:'¥'+Number(o.totalAmount||0).toFixed(2)},{label:'支付方式',value:this.displayPaymentMethod(o.paymentMethod)},{label:'创建时间',value:this.displayDateTime(o.createdAt)},{label:'支付时间',value:this.displayDateTime(o.paidAt)},{label:'当前状态',value:this.statusName(o.status)},...(o.occupiedSeconds!=null?[{label:'接单时长',value:this.occupiedText(o.occupiedSeconds)}]:[])]}},onLoad(q){this.dark=isDark();this.id=q.id||''},onShow(){this.load()},methods:{statusName(v){return({unpaid:'待付款',pending:'待接单',accepted:'已接单',serving:'服务中',completed:'已完成',refunding:'售后中',refunded:'已退款',cancelled:'已关闭'})[v]||v||'-'},statusTone(v){return({pending:'brand',accepted:'success',serving:'warning',completed:'neutral',refunding:'danger',refunded:'danger'})[v]||'neutral'},allowed(a){return(this.order?.allowedActions||[]).includes(a)},async load(){if(!this.id){this.error='缺少订单编号';this.loading=false;return}this.loading=true;try{this.order=await api.getWorkbenchOrder(this.id);this.error=''}catch(e){this.order=null;this.error=e.message||'订单不存在或无权查看'}finally{this.loading=false}},async act(action){try{await api.workbenchOrderAction(this.id,action);await this.load();uni.showToast({title:action==='reject'?'已提交退款审核':'操作成功',icon:'success'})}catch(e){uni.showToast({title:e.message||'操作失败',icon:'none'})}},openAfterSale(item){uni.navigateTo({url:'/pages/aftersale/detail?id='+item.id+'&workbench=1'})}}}
</script>
<style scoped>.workbench-detail{padding-bottom:48rpx}.summary,.card{margin:22rpx 28rpx;padding:28rpx;border-radius:24rpx;background:var(--surface);box-shadow:var(--shadow-card)}.summary,.link{display:flex;align-items:center;justify-content:space-between}.summary>view,.link>view{display:flex;flex-direction:column;gap:10rpx}.muted{color:var(--muted);font-size:22rpx}.row{min-height:78rpx;display:flex;align-items:center;justify-content:space-between;gap:24rpx;border-bottom:1rpx solid var(--line);font-size:23rpx}.row text:first-child{color:var(--muted)}.row text:last-child{max-width:470rpx;text-align:right}.log{padding:20rpx 0;border-bottom:1rpx solid var(--line)}.log>view{display:flex;justify-content:space-between;margin-bottom:8rpx}.actions{margin:26rpx 28rpx;display:flex;flex-direction:column;gap:16rpx}.secondary-btn{height:84rpx;display:flex;align-items:center;justify-content:center;border:2rpx solid var(--line);border-radius:44rpx}</style>
