<template>
  <view :class="['app-page','aftersale-page',{dark}]">
    <ui-header :title="id?'售后详情':'退款协调申请'" back />
    <template v-if="!id">
      <view class="card"><text>请先联系客服协调退款。提交申请不代表退款成功，平台审核后按结果处理。</text><view class="secondary-btn" @tap="contactService">联系客服</view></view>
      <view class="card"><text class="section-title">退款原因</text><picker :range="reasons" @change="reason=reasons[$event.detail.value]"><view class="picker">{{reason||'请选择原因'}}<ui-icon name="chevron-right" :size="28"/></view></picker><textarea v-model="description" maxlength="1000" placeholder="请说明问题和期望处理结果"/></view>
      <view :class="['primary-btn',{disabled:submitting}]" @tap="submit">{{submitting?'提交中':'提交退款协调申请'}}</view>
    </template>
    <template v-else-if="data">
      <view class="status-card"><text class="section-title">{{statusName(data.status)}}</text><text class="muted">{{data.aftersale_no||data.aftersaleNo}}</text></view>
      <view class="card"><view class="row"><text>订单号</text><text>{{data.orderNo}}</text></view><view class="row"><text>商品</text><text>{{data.productName}} · {{data.skuName}}</text></view><view class="row"><text>退款金额</text><text class="price">¥{{money(data.refund_amount||data.refundAmount)}}</text></view><view class="row"><text>申请原因</text><text>{{data.reason}}</text></view><view class="row"><text>申请说明</text><text>{{data.description||'无'}}</text></view><view v-if="data.provider_note" class="row"><text>服务方说明</text><text>{{data.provider_note}}</text></view><view v-if="data.review_note" class="row"><text>平台说明</text><text>{{data.review_note}}</text></view></view>
      <view class="card"><text class="section-title">售后流转</text><view v-for="(log,index) in data.logs||[]" :key="index" class="log"><view><text>{{statusName(log.toStatus)}}</text><text class="muted">{{displayDateTime(log.createdAt)}}</text></view><text class="muted">{{log.note||'-'}}</text></view></view>
      <view v-if="workbench&&data.status==='applied'" class="card"><textarea v-model="providerNote" maxlength="1000" placeholder="请填写处理说明"/><view class="actions"><view class="secondary-btn" @tap="providerAction('reject')">拒绝申请</view><view class="primary-btn" @tap="providerAction('approve')">同意申请</view></view></view>
    </template>
    <ui-page-status v-else-if="id" :loading="loading" title="售后详情加载失败" :description="error" @retry="load" />
  </view>
</template>
<script>
import{api}from'@/services/api';import{isDark}from'@/utils/app'
export default{data(){return{dark:false,id:'',orderId:'',workbench:false,data:null,loading:false,error:'',reason:'',description:'',providerNote:'',submitting:false,reasons:['服务方无法履约','服务内容与约定不符','重复下单','其他原因'],requestId:''}},onLoad(q){this.dark=isDark();this.id=q.id||'';this.orderId=q.orderId||'';this.workbench=q.workbench==='1';this.requestId=api.newRequestId('aftersale');if(this.id)this.load()},methods:{contactService(){uni.navigateTo({url:'/pages/service/customer?orderId='+this.orderId})},money(v){return Number(v||0).toFixed(2)},statusName(v){return({applied:'待服务方处理',provider_approved:'服务方已同意',provider_rejected:'服务方已拒绝',platform_reviewing:'平台审核中',approved:'平台已通过',rejected:'平台已驳回',refunded:'已退款',cancelled:'已取消'})[v]||v||'-'},async submit(){if(this.submitting)return;if(!this.orderId||!this.reason){uni.showToast({title:'请选择退款原因',icon:'none'});return}this.submitting=true;try{const result=await api.applyAfterSale(this.orderId,{reason:this.reason,description:this.description,evidence:[]},this.requestId);this.id=result.id;await this.load()}catch(e){uni.showToast({title:e.message||'售后申请提交失败',icon:'none'})}finally{this.submitting=false}},async load(){this.loading=true;try{this.data=this.workbench?await api.getWorkbenchAfterSale(this.id):await api.getAfterSale(this.id);this.error=''}catch(e){this.data=null;this.error=e.message||'售后申请不存在或无权查看'}finally{this.loading=false}},async providerAction(action){try{await api.workbenchAfterSaleAction(this.id,action,this.providerNote);await this.load();uni.showToast({title:'处理成功',icon:'success'})}catch(e){uni.showToast({title:e.message||'处理失败',icon:'none'})}}}}
</script>
<style scoped>.aftersale-page{padding-bottom:50rpx}.card,.status-card{margin:22rpx 28rpx;padding:28rpx;border-radius:24rpx;background:var(--surface);box-shadow:var(--shadow-card)}.status-card{display:flex;flex-direction:column;gap:10rpx}.muted{color:var(--muted);font-size:22rpx}.picker,.row{min-height:84rpx;display:flex;align-items:center;justify-content:space-between;gap:24rpx;border-bottom:1rpx solid var(--line)}textarea{box-sizing:border-box;width:100%;height:220rpx;margin-top:22rpx;padding:20rpx;border:1rpx solid var(--line);border-radius:18rpx}.aftersale-page>.primary-btn{margin:30rpx 28rpx}.disabled{opacity:.55}.row text:first-child{color:var(--muted)}.row text:last-child{max-width:470rpx;text-align:right}.price{color:var(--primary);font-weight:800}.log{padding:20rpx 0;border-bottom:1rpx solid var(--line)}.log>view{display:flex;justify-content:space-between;margin-bottom:8rpx}.actions{display:flex;gap:16rpx;margin-top:20rpx}.actions>view{flex:1}.secondary-btn{height:82rpx;display:flex;align-items:center;justify-content:center;border:2rpx solid var(--line);border-radius:42rpx}</style>
