<template><view :class="['app-page',{dark}]"><ui-header title="打手入驻审核" back/><view v-if="!submitted"><view class="apply-hero"><text class="hero-title">加入平台打手团队</text><text>身份核验与入驻资格一次提交、统一审核</text></view><view class="apply-card" v-if="history.length"><text class="apply-title">申请进度</text><view v-for="item in history" :key="item.id" class="history-row"><text>{{statusLabel(item.status)}}</text><text class="review-note">{{item.reviewNote||''}}</text></view></view><view class="apply-card"><text class="apply-title">入驻与身份资料</text><text class="muted">通过审核后，由平台为你绑定商品；你不需要创建店铺。</text><view v-for="field in fields" :key="field.key" class="apply-row"><text>{{field.label}}</text><input v-model="form[field.key]" :type="field.type||'text'" :maxlength="field.max||100" :placeholder="field.placeholder"/></view><text class="muted">已有审核通过的身份资料会继续使用，不重复认证。</text></view><view class="agree" @tap="agreed=!agreed"><view :class="['checkbox',{on:agreed}]"><ui-icon v-if="agreed" name="check" :size="22"/></view><text>确认资料真实并同意</text><text @tap.stop="openPrivacy">《隐私政策》</text></view><text class="error" v-if="error">{{error}}</text><view class="primary-btn submit" @tap="submit">{{submitting?'提交中…':hasActive?'已有申请，请查看进度':'提交审核'}}</view></view><view v-else class="result"><ui-icon name="check-circle" :size="110"/><text class="section-title">申请已提交</text><text class="muted">入驻和身份资料将由平台统一审核</text><view class="primary-btn" @tap="back">返回我的</view></view></view></template>
<script>
import {api} from '@/services/api'
import {confirmSensitiveConsent,SENSITIVE_CONSENT_VERSION} from '@/services/sensitive-consent'

import {isDark} from '@/utils/app'
export default{
 data(){return{dark:false,agreed:false,submitted:false,submitting:false,error:'',history:[],form:{nickname:'',name:'',phone:'',idNumber:'',remark:''},fields:[{key:'nickname',label:'打手昵称',placeholder:'填写服务昵称'},{key:'name',label:'本人姓名',placeholder:'填写真实姓名'},{key:'idNumber',label:'身份证号',placeholder:'填写本人身份证号',max:18},{key:'phone',label:'联系电话',placeholder:'填写手机号',type:'number',max:11},{key:'remark',label:'服务介绍',placeholder:'擅长的服务、经验等'}]}},
 computed:{hasActive(){return this.history.some(x=>['pending','approved'].includes(x.status))}},
 onLoad(){this.dark=isDark();this.loadHistory()},
 methods:{
 statusLabel(s){return({pending:'审核中',approved:'已通过',rejected:'已驳回'})[s]||s},
 async loadHistory(){try{this.history=await api.getApplications('player');const previous=this.history[0];if(previous?.status==='rejected'&&!this.form.name&&!this.form.phone){this.form.nickname=previous.displayName||'';this.form.name=previous.realName||'';this.form.phone=previous.phone||'';this.form.remark=previous.remark||''}}catch(e){this.error=e.message}},
 openPrivacy(){uni.navigateTo({url:'/pages/common/document?type=privacy'})},
 async submit(){if(this.submitting||this.hasActive)return;if(!this.form.nickname||!this.form.name||!/^1[3-9]\d{9}$/.test(this.form.phone)){this.error='请填写昵称、真实姓名及正确的手机号';return}if(!this.agreed){this.error='请确认资料并阅读隐私政策';return}this.submitting=true;try{if(!await confirmSensitiveConsent('application')){this.error='未同意处理身份信息，本次未提交';return}await api.submitApplication({...this.form,type:'player',sensitiveConsent:true,sensitiveConsentVersion:SENSITIVE_CONSENT_VERSION});uni.hideKeyboard();this.form={nickname:'',name:'',phone:'',idNumber:'',remark:''};this.submitted=true;this.error=''}catch(e){this.error=e.message||'提交失败'}finally{this.submitting=false}},
 back(){uni.reLaunch({url:'/pages/profile/index'})}
 }
}
</script>
<style scoped>.apply-hero{margin:24rpx 28rpx;padding:36rpx;display:flex;flex-direction:column;align-items:center;gap:12rpx;border-radius:26rpx;background:linear-gradient(135deg,#5f75e6,#8669d8);color:#fff;text-align:center;box-shadow:0 16rpx 40rpx rgba(78,91,190,.2)}.hero-icon{width:94rpx;height:94rpx;display:flex;align-items:center;justify-content:center;border-radius:30rpx;background:rgba(255,255,255,.16)}.hero-title{margin-top:8rpx;font-size:34rpx;font-weight:800}.apply-hero>text:last-child{font-size:23rpx;opacity:.82}.merchant-banner{margin:24rpx 28rpx;padding:24rpx;display:flex;align-items:center;gap:14rpx;border-radius:22rpx;background:var(--accent-soft)}.merchant-banner>text{flex:1;font-size:23rpx}.merchant-banner>view{padding:12rpx 22rpx;border-radius:28rpx;background:var(--accent);color:#fff;font-size:23rpx}.merchant-banner small{display:none}.apply-card{margin:24rpx 28rpx;padding:26rpx;border-radius:24rpx;background:var(--surface);box-shadow:var(--shadow-card)}.apply-title{display:block;font-size:30rpx;font-weight:800}.apply-card>.muted{display:block;margin:10rpx 0 20rpx;font-size:23rpx}.history-row{padding:18rpx 0;border-bottom:1rpx solid var(--line)}.history-row>view{display:flex;justify-content:space-between}.review-note{display:block;margin-top:10rpx;color:var(--primary);font-size:22rpx}.apply-row{min-height:104rpx;display:flex;align-items:center;border-bottom:1rpx solid var(--line)}.apply-row>text{width:180rpx;color:var(--text-secondary)}.apply-row input{flex:1;color:var(--text);font-size:25rpx}.agree{display:flex;align-items:center;gap:10rpx;margin:20rpx 30rpx;color:var(--muted);font-size:23rpx}.checkbox{width:32rpx;height:32rpx;display:flex;align-items:center;justify-content:center;border:2rpx solid #c8c8c8;border-radius:50%}.checkbox.on{background:var(--primary);border-color:var(--primary)}.error{display:block;margin:12rpx 55rpx;color:var(--primary);font-size:23rpx}.submit{margin:36rpx 78rpx}.submit.disabled{opacity:.48}.result{position:fixed;z-index:100;top:0;right:0;bottom:0;left:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:24rpx;padding:60rpx;background:var(--surface)}.result .primary-btn{width:100%;margin-top:40rpx}</style>
