<template>
  <view :class="['app-page',{dark}]">
    <ui-header title="个人资料" back />
    <view class="form-card profile-form">
      <view class="form-row" @tap="showAvatar=true"><text class="form-label">头像：</text><image v-if="form.avatar" class="avatar" :src="form.avatar" mode="aspectFill"/><view v-else class="avatar placeholder"><ui-icon name="user" :size="42" tone="muted"/></view></view>
      <view class="form-row"><text class="form-label">账号：</text><text class="form-input">{{form.account}}</text></view>
      <view class="form-row"><text class="form-label">昵称：</text><input v-model="form.nickname" class="form-input" /></view>
      <picker mode="date" :value="form.birthday" @change="form.birthday=$event.detail.value"><view class="form-row"><text class="form-label">生日：</text><text class="form-input">{{form.birthday||'请选择出生日期'}}</text></view></picker>
      <view class="form-row"><text class="form-label">性别：</text><view class="gender"><view :class="{on:form.gender==='male'}" @tap="form.gender='male'"><ui-icon name="male" :size="27"/><text>男</text></view><view :class="{on:form.gender==='female'}" @tap="form.gender='female'"><ui-icon name="female" :size="27"/><text>女</text></view></view></view>
      <view class="form-row"><text class="form-label">城市：</text><input v-model="form.city" class="form-input" placeholder="请输入所在城市" /></view>
    </view>
    <view class="primary-btn submit" @tap="save">提交</view>
    <view v-if="showAvatar" class="sheet-mask" @tap="showAvatar=false"><view class="avatar-sheet" @tap.stop><view class="sheet-item" @tap="chooseImage('album')">从相册选择</view><view class="sheet-item" @tap="chooseImage('camera')">拍照</view><view class="sheet-item cancel" @tap="showAvatar=false">取消</view></view></view>
  </view>
</template>
<script>import{isDark}from'@/utils/app';import{api}from'@/services/api';export default{data(){return{dark:false,showAvatar:false,saving:false,form:{avatar:'',account:'',nickname:'',birthday:'',gender:'unknown',city:''}}},onLoad(){this.dark=isDark();api.getProfile().then(user=>{this.form={...this.form,...user}}).catch(e=>uni.showToast({title:e.message||'资料加载失败，请重试',icon:'none'}))},methods:{chooseImage(sourceType){uni.chooseImage({count:1,sourceType:[sourceType],success:async r=>{try{uni.showLoading({title:'上传中'});this.form.avatar=await api.uploadImage(r.tempFilePaths[0]);this.showAvatar=false}catch(e){uni.showToast({title:e.message||'上传失败',icon:'none'})}finally{uni.hideLoading()}}})},async save(){if(this.saving||!this.form.nickname.trim())return;this.saving=true;try{await api.updateProfile(this.form);uni.navigateBack()}catch(e){uni.showToast({title:e.message||'保存失败',icon:'none'})}finally{this.saving=false}}}}</script>
<style scoped>.profile-form{padding-top:20rpx;padding-bottom:20rpx}.avatar{margin-left:auto;width:78rpx;height:78rpx;border-radius:18rpx}.placeholder{display:flex;align-items:center;justify-content:center;background:var(--brand-soft)}.gender{margin-left:auto;display:flex;gap:14rpx;color:var(--muted)}.gender>view{height:54rpx;padding:0 18rpx;display:flex;align-items:center;gap:5rpx;border:1rpx solid var(--line);border-radius:28rpx}.gender .on{border-color:var(--brand);background:var(--brand-soft);color:var(--brand)}.submit{margin:28rpx 56rpx}.sheet-mask{position:fixed;z-index:200;top:0;right:0;bottom:0;left:0;display:flex;align-items:flex-end;background:rgba(0,0,0,.58)}.avatar-sheet{width:100%;padding-bottom:env(safe-area-inset-bottom);background:var(--surface);border-radius:28rpx 28rpx 0 0}.sheet-item{height:104rpx;display:flex;align-items:center;justify-content:center;border-bottom:1rpx solid var(--line);background:var(--surface);color:var(--text);font-size:28rpx;line-height:104rpx}.cancel{margin-top:12rpx;border-top:8rpx solid var(--bg)}</style>
